#!/bin/bash
#
# build-offline.sh — Creates a self-contained offline slideshow bundle
#
# Usage:
#   ./build-offline.sh           # creates offline/ folder
#   ./build-offline.sh --zip     # also creates .zip for USB transfer
#
# Prerequisites:
#   - Internet connection (downloads photos from Google Drive)
#   - python3, curl
#
# Output:
#   offline/
#     index.html      (patched for local paths)
#     photos.js       (local file references)
#     photos/         (downloaded images)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OFFLINE_DIR="$SCRIPT_DIR/offline"
PHOTOS_DIR="$OFFLINE_DIR/photos"
SRC_PHOTOS_JS="$SCRIPT_DIR/photos.js"
ZIP_FLAG="$1"

if [ ! -f "$SRC_PHOTOS_JS" ]; then
  echo "Error: photos.js not found. Run build-photos-js.sh first."
  exit 1
fi

echo "Setting up offline directory..."
mkdir -p "$PHOTOS_DIR"

# ── Download splash image ──
SPLASH_URL="https://lh3.googleusercontent.com/d/1G6M96itCP7OLS5YRSy9OWJUuhbzCgNif"
if [ ! -f "$PHOTOS_DIR/splash.jpg" ]; then
  echo "Downloading splash image..."
  curl -sL "${SPLASH_URL}=w1920" -o "$PHOTOS_DIR/splash.jpg"
fi

# ── Download all photos ──
echo "Downloading photos..."
python3 << 'PYEOF'
import re, subprocess, os, time

photos_js = open(os.environ.get("SRC_PHOTOS_JS", "photos.js")).read()
photos_dir = os.environ.get("PHOTOS_DIR", "offline/photos")

# Parse URL and filename from each line
entries = re.findall(
    r'"(https://lh3\.googleusercontent\.com/d/[^"]+)".*?//\s*(.+)',
    photos_js
)

total = len(entries)
downloaded = 0
skipped = 0
failed = 0

for i, (url, name) in enumerate(entries):
    name = name.strip().rstrip(',')
    # Sanitize filename
    safe_name = re.sub(r'[^\w.\-]', '_', name)
    dest = os.path.join(photos_dir, safe_name)

    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        skipped += 1
        continue

    try:
        result = subprocess.run(
            ["curl", "-sL", f"{url}=w1920", "-o", dest],
            timeout=30, capture_output=True
        )
        if result.returncode == 0 and os.path.getsize(dest) > 0:
            downloaded += 1
        else:
            failed += 1
            if os.path.exists(dest):
                os.remove(dest)
    except Exception:
        failed += 1
        if os.path.exists(dest):
            os.remove(dest)

    if (i + 1) % 10 == 0:
        print(f"  {i + 1}/{total}...")
    time.sleep(0.3)

print(f"\nDownloaded: {downloaded}  Skipped (existing): {skipped}  Failed: {failed}")
PYEOF

# ── Generate offline photos.js ──
echo "Generating offline photos.js..."
python3 << 'PYEOF'
import re, os

photos_js = open(os.environ.get("SRC_PHOTOS_JS", "photos.js")).read()
photos_dir = os.environ.get("PHOTOS_DIR", "offline/photos")
offline_dir = os.environ.get("OFFLINE_DIR", "offline")

entries = re.findall(
    r'"(https://lh3\.googleusercontent\.com/d/[^"]+)".*?//\s*(.+)',
    photos_js
)

local_paths = []
for url, name in entries:
    name = name.strip().rstrip(',')
    safe_name = re.sub(r'[^\w.\-]', '_', name)
    if os.path.exists(os.path.join(photos_dir, safe_name)):
        local_paths.append(safe_name)

lines = [
    '// photos.js — local photo paths (auto-generated by build-offline.sh)',
    '// Do not edit by hand',
    'const PHOTOS = ['
]
for i, p in enumerate(local_paths):
    comma = ',' if i < len(local_paths) - 1 else ''
    lines.append(f'  "photos/{p}"{comma}')
lines.append('];')

out_path = os.path.join(offline_dir, "photos.js")
with open(out_path, "w") as f:
    f.write('\n'.join(lines) + '\n')

print(f"Wrote {len(local_paths)} local photo entries to offline/photos.js")
PYEOF

# ── Copy and patch index.html ──
echo "Patching index.html for offline use..."
python3 << PYEOF
import re

with open("$SCRIPT_DIR/index.html") as f:
    html = f.read()

# Local splash image
html = html.replace(
    "https://lh3.googleusercontent.com/d/1G6M96itCP7OLS5YRSy9OWJUuhbzCgNif",
    "photos/splash.jpg"
)

# Remove PWA meta tags, manifest, apple-touch-icon
for pattern in [
    r'<meta name="apple-mobile-web-app[^>]*>\n?',
    r'<meta name="mobile-web-app[^>]*>\n?',
    r'<link rel="manifest"[^>]*>\n?',
    r'<link rel="apple-touch-icon"[^>]*>\n?',
]:
    html = re.sub(pattern, '', html)

# Remove install link element
html = re.sub(r'\s*<a href="install\.html"[^>]*>[^<]*</a>\n?', '\n', html)

# Remove install-link JS event listener block
html = re.sub(
    r"\s*document\.getElementById\('install-link'\)\.addEventListener\('click',\s*\(e\)\s*=>\s*\{\s*e\.stopPropagation\(\);\s*\}\);\n?",
    '\n',
    html
)

with open("$OFFLINE_DIR/index.html", "w") as f:
    f.write(html)
PYEOF

echo ""
echo "Offline bundle ready: $OFFLINE_DIR/"

# ── Optional zip ──
if [ "$ZIP_FLAG" = "--zip" ]; then
  ZIP_FILE="$SCRIPT_DIR/carol-kellogg-lavoie-offline.zip"
  echo "Creating zip..."
  cd "$SCRIPT_DIR"
  zip -rq "$ZIP_FILE" offline/
  echo "Zip created: $ZIP_FILE"
fi

echo "Done. Open offline/index.html in a browser — no internet needed."
