#!/bin/bash
#
# build-photos-js.sh — Generates photos.js from a public Google Drive folder
#
# Usage:
#   ./build-photos-js.sh FOLDER_ID
#
# Example:
#   ./build-photos-js.sh 1OKIYImdYoSRTqRav727q1p691lJCT-11
#
# Prerequisites:
#   - The Drive folder must be shared as "Anyone with the link"
#   - python3 must be installed
#
# What it does:
#   1. Fetches the embedded folder view from Google Drive
#   2. Extracts file IDs and names from the HTML
#   3. Filters to supported image formats (jpg, jpeg, png, gif, webp, bmp)
#   4. Writes photos.js with lh3.googleusercontent.com direct URLs

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$SCRIPT_DIR/photos.js"

if [ -z "$1" ]; then
  echo "Usage: $0 FOLDER_ID"
  echo ""
  echo "Get the folder ID from the Google Drive share URL:"
  echo "  https://drive.google.com/drive/folders/FOLDER_ID"
  exit 1
fi

FOLDER_ID="$1"

echo "Fetching file list from Google Drive folder..."

python3 << PYEOF
import urllib.request
import re
import json

folder_id = "$FOLDER_ID"
url = f"https://drive.google.com/embeddedfolderview?id={folder_id}"
req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
resp = urllib.request.urlopen(req)
html = resp.read().decode("utf-8", errors="replace")

# Extract file entries: id="entry-FILEID" ... flip-entry-title">FILENAME</div>
entries = re.findall(
    r'id="entry-([A-Za-z0-9_-]+)"[^>]*>.*?<div class="flip-entry-title">([^<]+)</div>',
    html, re.DOTALL
)

if not entries:
    print("Error: No files found. Is the folder publicly shared?")
    exit(1)

# Filter to supported image formats (skip HEIC — browsers can't display it)
supported = ('.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp')
files = [{"id": fid, "name": name} for fid, name in entries
         if name.lower().endswith(supported)]

files.sort(key=lambda f: f['name'])

# Write photos.js
lines = [
    '// photos.js — Google Drive image URLs (auto-generated by build-photos-js.sh)',
    '// Do not edit by hand',
    'const PHOTOS = ['
]
for i, f in enumerate(files):
    comma = ',' if i < len(files) - 1 else ''
    lines.append(f'  "https://lh3.googleusercontent.com/d/{f["id"]}"{comma}  // {f["name"]}')
lines.append('];')

with open("$OUTPUT", "w") as out:
    out.write('\n'.join(lines) + '\n')

print(f"Found {len(entries)} total files in Drive folder")
print(f"Skipped {len(entries) - len(files)} unsupported formats (HEIC, etc.)")
print(f"Wrote {len(files)} photos to photos.js")
PYEOF

echo ""
echo "Done. Deploy to GitHub Pages or open index.html to test."
